release = ["-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_DD_TYPE=CUDD", "-DPLUGIN_MEDDLY_OPERATIONS_ENABLED=FALSE"]
debug = ["-DCMAKE_BUILD_TYPE=Debug", "--DCMAKE_DD_TYPE=CUDD", "-DPLUGIN_MEDDLY_OPERATIONS_ENABLED=FALSE"]
# DD Libs
release_cudd = ["-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_DD_TYPE=CUDD", "-DPLUGIN_MEDDLY_OPERATIONS_ENABLED=FALSE"]
release_cudd_add = ["-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_DD_TYPE=CUDDADD", "-DPLUGIN_MEDDLY_OPERATIONS_ENABLED=FALSE"]
release_sylvan = ["-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_DD_TYPE=SYLVAN", "-DPLUGIN_MEDDLY_OPERATIONS_ENABLED=FALSE"]
release_buddy = ["-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_DD_TYPE=BUDDY", "-DPLUGIN_MEDDLY_OPERATIONS_ENABLED=FALSE"]
release_cacbdd = ["-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_DD_TYPE=CACBDD", "-DPLUGIN_MEDDLY_OPERATIONS_ENABLED=FALSE"]
release_meddly = ["-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_DD_TYPE=MEDDLY"]

releasenolp = ["-DCMAKE_BUILD_TYPE=Release", "-DUSE_LP=NO", "-DCMAKE_DD_TYPE=CUDD", "-DPLUGIN_MEDDLY_OPERATIONS_ENABLED=FALSE"]
debugnolp = ["-DCMAKE_BUILD_TYPE=Debug", "-DUSE_LP=NO", "-DCMAKE_DD_TYPE=CUDD", "-DPLUGIN_MEDDLY_OPERATIONS_ENABLED=FALSE"]
minimal = ["-DCMAKE_BUILD_TYPE=Release", "-DDISABLE_PLUGINS_BY_DEFAULT=YES", "-DCMAKE_DD_TYPE=CUDD", "-DPLUGIN_MEDDLY_OPERATIONS_ENABLED=FALSE"]

DEFAULT = "release"
DEBUG = "debug"
